### PR TITLE
Change to dcterms:rights; closes #636

### LINKED ISSUE #636: Change "license" to map to dct:rights
@kestlund, @anarchivist, @aisaac 
e.g. rightsstatements.org

### PR DESCRIPTION
**Pull request by azaroth42**
If we merge this PR, then the live, current context will change. 
Confirm agreement that this doesn't need to be delayed until 2.1 is released please.

### CODE REVIEW

**Comment by jpstroop** [comment]
This is the right thing to do, even though it breaks our rules. I don't like it, but practically speaking, it makes sense and no one will likely notice.

**Comment by jpstroop** [comment]
Shrugs. Should there at least be a note to IIIF discuss?

**Comment by azaroth42** [comment]
Note to IIIF-Discuss seems good course of action. :+1:s on PR with a note describing the change?

**Comment by tomcrane** [comment]
:+1: , and maybe tweak the description in the Presentation API spec to convey that viewer implementers don't have to use the label "license"  when they display the link to a user; that label could be "license/rights" or something.

**Comment by zimeon** [comment]
:+1: to going ahead. I think we are invoking the _in practice_ clause in semver... if a change is technically breaking but nobody is using the feature that is broken, the change is not breaking. Also agree on a note to IIIF-Discuss and a change to suggest the use or _rights_ or _license/rights_ in UI.

**Comment by mikeapp** [comment]
:+1: Agreed, and on note to IIIF-Discuss and suggested label change.

**Pull request merged**
