### PR TITLE
clarify max canonical

### LINKED ISSUE #883: What is the canonical form of `max` size in 2.1?
Presumably it will be `max` in 3.0. The calculated `w,` until then?

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

### PR DESCRIPTION
**Pull request by jpstroop**
Closes #883

### CODE REVIEW

**Comment by jpstroop** [comment]
better?

**Comment by jpstroop** [comment]
@azaroth42 or @tomcrane ?

**Comment by azaroth42** [comment]
:+1: but 2.1.1 so not merging yet, right?

**Comment by azaroth42** [comment]
Merging on 4.

**Pull request merged**
