### PR TITLE
Fix typos from Rob Lancefield

### LINKED ISSUE #804: Typos
Thanks to Rob Lancefield for the careful reading!

## Image API

- [x] 4.2. Size First table, row 2, col 2: "This is the same as full if none of these are properties are provided." The first "are" should be deleted. 

- [x] 4.6. Order of Implementation Second paragraph, only sentence: "The parameters should be interpreted as if the the sequence of image manipulations were:" The last "the" should be deleted.

- [x] 4.7. Canonical URI Syntax  First table, row 2, col 2, "Note": "The the size keyword...." The second "the" should be deleted.

- [x] 5.2. Technical Properties Second table, row 2, col 3: "aas an integer" should be "as an integer."

- [x] 5.3. Profile Description Second paragraph, fifth sentence: "Servers must ensure that sizes specified within any sizes or tiles properties are with any size limits expressed." The "with" seems to want to be "within," unless I'm misreading intended sense.

- [x] 7.2. Error Conditions First table, row 1, col 2: UK spelling of "fulfil" may want to become US "fulfill" for consistency in the context of this document.

- [x] Appendix A. Implementation Notes Seventh bullet note: "for a full imagine" should be "for a full image."

## Presentation API

- [x] 2.1. Basic Types First sentence in "Sequence": "of a the object" wants to be "of an object."

- [x] 3.1. Descriptive Properties Last line: "Other resources types" wants to be either "Other resource types" or "A resource of any other type"

- [x] 5.8. Collection First paragraph, last sentence: "Embedded collections should have their own URI from which the description is also made available." May be clearer as "An [or: Each] embedded collection should have its own URI from which the description is also made available."

- [x] 6.1. Segments Second paragraph, first sentence: "Note that if both there are segments of both image and canvas" wants deletion of the first "both."

- [x] 6.3. Choice of Alternative Resources Last paragraph, last sentence: "this can be either done such that the entire image is switched to change state, or only the section of the image" wants to be "this can be done such that either the entire image is switched to change state, or only the section of the image"

## Search API

- [x] 1.1. Use Cases Trivial but noted in passing: Some items in bullet list end with periods, others don't.

- [x] 2. Overview Second paragraph, last sentence: "annotation lists" wants to be "Annotation lists"

- [x] 3. Search First sentence: "uri" wants to be "URI"

- [x] 3.3.1. Simple Lists Second paragraph, last sentence: "derefencable" wants to be "dereferenceable"

- [x] 3.4 Search API Specific Responses First paragraph, only sentence: UK spelling of "fulfil" may want to become US "fulfill" for consistency in the context of this document.

- [x] 3.4 Second paragraph, first sentence: "As these response" wants to be "As these responses"

- [x] 3.4.4. Multi-Annotations Hits First paragraph, last sentence: "on the method that the text and annotations were generated" would read more clearly as "on the method by which the text and annotations were generated"

- [x] 5. Property Definitions Under "count": Since these definitions are scoped to the context of server response to one given query, "A number of times that a term appears" seems to want to be "The number of times that a term appears."

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #804

### CODE REVIEW

**Comment by azaroth42** [comment]
Also Closes #805.

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
:+1: and huge thanks to Rob Lancefield!

**Comment by zimeon** [comment]
Three sets of eyes checking non-normative change seems enough, will merge.

**Pull request merged**
