### PR TITLE
ncsu news announcement

### PR DESCRIPTION
**Pull request by srabun**
Announcing NCSU joining consortium plus Nubian Message implementation and other search inside collections.

http://ncsu_news.iiif.io/news/

http://ncsu_news.iiif.io/news/2016/09/12/ncsu-joins-iiifc/

### CODE REVIEW

**Comment by azaroth42** [comment]
Very nice! :+1: from me

**Comment by mikeapp** [comment]
One question/comment: the links to the APIs go to specific versions, not sure if it would be better to link to the latest stable or just `/` and let the redirect do its thing.

**Comment by srabun** [comment]
@mikeapp will the current links break when new specs are published? I don't mind changing the links if that's preferred

**Comment by jpstroop** [comment]
I don't feel strongly about the links either way--they won't break with new specs. :+1: overall!

**Comment by zimeon** [comment]
Since the text says just "IIIF APIs", I'd go with unversioned links, otherwise :+1:

**Comment by srabun** [comment]
@zimeon So there is the "IIIF APIs" link but also above that in the first paragraph there are links to the Image, Presentation, and Search APIs specifically...

**Comment by mikeapp** [comment]
@srabun  For example, the url `http://iiif.io/api/search/` will always redirect to the latest version of the API.  If you link to a specific version it will eventually be superseded by a new version and become obsolete.

**Comment by srabun** [comment]
Roger. I will go ahead and update the links so we will have our bases covered

**Comment by azaroth42** [comment]
All comments resolved with +1s, merging...

**Comment by srabun** [comment]
Ok, I made the changes - links to specific APIs are now un-versioned

**Pull request merged**
