### PR TITLE
Add reference to notes, closes #681

### LINKED ISSUE #681: Add link to annexes to /apis/ list of specs
What it says on the tin.

### PR DESCRIPTION
**Pull request by azaroth42**
Does WISOTT.

### CODE REVIEW

**Comment by zimeon** [comment]
:+1: http://681_linkannex.iiif.io/api has Notes section. (We might want to expand a some later stage but for now lets get this out, clearly an improvement)

**Comment by mikeapp** [comment]
+1

**Comment by jpstroop** [comment]
:+1:

**Comment by tomcrane** [comment]
:+1:

**Pull request merged**
