### PR TITLE
676 frontpage

### LINKED ISSUE #676: Replace front page demo with carousel of showcase tiles
The try it demo on the front page is horribly out of date (v1.1) and while it was great when IIIF was more technically focused, we've outgrown it as a community.

As a replacement, I propose a carousel of the showcase tiles.  We should also link to showcase.iiif.io in the header navigation bar, and solicit more tiles.

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #676

### CODE REVIEW

**Comment by jpstroop** [comment]
:+1: following a squash

**Comment by tomcrane** [comment]
I have updated the UV info - but it depends on a PR on showcase.iiif.io as well.

**Comment by mikeapp** [comment]
:+1: overall but would suggest adjusting the `wrapper` class width to 800px (i.e., exactly two tiles wide)

**Comment by zimeon** [comment]
:+1: but agree with @mikeapp that exaclty two tiles displayed would be good

**Comment by azaroth42** [comment]
Agreed, will fix tile width and squash

**Comment by azaroth42** [comment]
Responsiveness fixed, squashed commits. GTG?

**Comment by zimeon** [comment]
:+1: http://676_frontpage.iiif.io/ is good to go to me... responsive 1,2,3 tiles, yum

**Comment by jpstroop** [comment]
:+1:

**Pull request merged**
