### PR TITLE
Iiifc info

### PR DESCRIPTION
**Pull request by srabun**
added the IIIF-C FAQ page at http://iiifc_info.iiif.io/community/consortium/faq/ , linked from http://iiifc_info.iiif.io/community/consortium

This is the first version, I will be adding more content to cover examples and maybe even a map with pins in it to represent location of all IIIF-C members, and other potential ideas for improvement. It's iterative.

@azaroth42 @jpstroop @mikeapp @zimeon

### CODE REVIEW

**Comment by srabun** [comment]
move general IIIF questions (not IIIF-C specific) to a separate page, link to it from the "Why IIIF" section in IIIF-C FAQ

**Comment by azaroth42** [comment]
:+1: from me!

**Comment by zimeon** [comment]
:+1:

**Comment by jpstroop** [comment]
I was only able to give it a quick skim, but it looks good from 10K feet.

**Pull request merged**
