### PR TITLE
Patterns document tweaks after 2017-03-15 community call

### LINKED ISSUE #1100: Fix "Design Patterns" to more consistently use patterns rather than principles
We changed the name (IIIF Design Patterns) and URI (http://iiif.io/api/annex/notes/design_patterns/) of the doc to patterns a while back but we need to go through and be more consistent with the term. (An perhaps the label in github ;-) )

### PR DESCRIPTION
**Pull request by zimeon**
Changes to fix #1100 #1041 #1036 that were the remaining changes to make after final review on the 2017-03-15 community call. Also adds a changelog entry for today noting this review.

### CODE REVIEW

**Comment by srabun** [comment]
Looks good to me!

**Comment by mikeapp** [comment]
👍  Would be ok with removing discuss links

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
Redeployed the branch: http://patterns_tweaks.iiif.io/api/annex/notes/design_patterns/

Looks good to me too. :+1:

**Comment by tomcrane** [comment]
and 👍

**Pull request merged**
