### PR TITLE
Validity for all viewingHints

### LINKED ISSUE #878: Clarify viewingHint validity
The viewingHint table should be consistent, with each entry starting with the validity.  Currently the canvas hints do not say that they're only valid on canvases.
(From iiif-discuss)

Open question as to whether this is a patch version change, as it makes the intended normative requirement explicit?

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

### PR DESCRIPTION
**Pull request by azaroth42**
Fixes #878. Adds validity for canvas VHs and makes the text more consistent.

### CODE REVIEW

**Comment by zimeon** [comment]
:+1: looks good

**Comment by azaroth42** [comment]
Deployed:  http://viewinghint.iiif.io/api/presentation/2.0/#technical-properties

**Comment by tomcrane** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Pull request merged**
