### PR TITLE
Script to generate robots.txt

### PR DESCRIPTION
**Pull request by jpstroop**
As mentioned in #824. With a little finagling @eefahy might be able to hook this into the cap deploy.

### CODE REVIEW

**Comment by azaroth42** [comment]
:+1: Haven't tested, but looks good. And at worst harmless.

**Comment by mikeapp** [comment]
:+1: looks good

**Comment by zimeon** [comment]
:+1: looks good

**Comment by zimeon** [comment]
Changing to :-1: on the idea of having `Disallow:` for old versions of the specs. While this might help with our presence in Google, we are also saying to web archiving systems etc. that we don't want the old specs harvested -- when we do. @azaroth42 says that IA uses `robots.txt` both to control harvesting and as a retrospective filter on what is visible, so adding `Disallow` for the old specs would vanish them from IA.

**Comment by zimeon** [comment]
See also #838

**Comment by mikeapp** [comment]
Also :-1: due to archiving concerns.

**Comment by azaroth42** [comment]
Agree that the web archiving issue is problematic. :-1:

**Comment by jpstroop** [comment]
Yup, 👎 based on our discussion. Closing.

**Pull request closed without merging**
