### PR TITLE
Fix dcterms/types typo

### LINKED ISSUE #786: dcterms:Image is not a thing --> dctypes
Fix.

### PR DESCRIPTION
**Pull request by azaroth42**
Non normative typo fix to a spec, fixes #786.

### CODE REVIEW

**Comment by zimeon** [comment]
:+1: when CI issue addressed

**Comment by jpstroop** [comment]
I had to fix that link on my branch for the scrolling hashes feature as well. I think we need to think about how long it's really necessary to keep links to random restaurants and hotels post-meetings.

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
Someone can merge :) (just not me)

**Comment by zimeon** [comment]
Rebased so CI now happy, will merge

**Pull request merged**
