### PR TITLE
Fix search contexts

### LINKED ISSUE #938: Search API context is missing wrapping `"@context": { .. }`
The Search API context: http://iiif.io/api/search/1/context.json is not a valid context, it needs `{ "@context": { ... } }` around it

### PR DESCRIPTION
**Pull request by zimeon**
Fixes #938

### CODE REVIEW

**Comment by jpstroop** [comment]
I don't have a way to test, but seems correct. :+1:

**Comment by azaroth42** [comment]
:+1: from me too

**Comment by tomcrane** [comment]
👍 When live, a chunk of Search JSON-LD will work properly in http://json-ld.org/playground/

**Comment by mikeapp** [comment]
👍

**Pull request merged**
