### PR TITLE
#674 Let's link editor names to ORCID iDs in the specs

### LINKED ISSUE #674: Let's link editor names to ORCID iDs in the specs
I think we should link editor names to ORCID iDs in the specs. This provides a future-proof way for us to provide descriptions of ourselves and links to other ids. See, for example, <http://www.openarchives.org/ore/0.9/jsonld>. I see 3 out of 5 of us have ORCID iDs already.

### PR DESCRIPTION
**Pull request by mikeapp**
Closes #674 
Web site changes only.

### CODE REVIEW

**Comment by zimeon** [comment]
Hmmm... http://674_orcid_for_editors.iiif.io/api/image/2.1/ shows 404, http://674_orcid_for_editors.iiif.io/ shows apache test page -- something wrong with test server? @azaroth42 ...

**Comment by jpstroop** [comment]
I rebased and deployed, should be there now: http://674_orcid_for_editors.iiif.io/api/image/2.0/

:+1:

**Comment by azaroth42** [comment]
Can we bold the name or otherwise make it stand out a little more? It's
cluttered looking at the moment, IMO.

On Sun, Feb 7, 2016 at 9:06 AM, Jon Stroop <notifications@github.com> wrote:

> I rebased and deployed, should be there now:
> http://674_orcid_for_editors.iiif.io/api/image/2.0/
>
> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/iiif.io/pull/701#issuecomment-181051623>.
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by jpstroop** [comment]
I had the same thought, though I didn't think of bolding the names. Making the names the Orcid links would also de-clutter things.

**Comment by azaroth42** [comment]
Or put institution and orcid on a second line?
When ORCID finds all my publications even remotely close to google scholar, and lets me link to all my other identities, I'll retire my personal site.

**Comment by jpstroop** [comment]
I'm fine w/ bolding. I think we should avoid a second line. Could you link to your personal site from ORCID?

**Comment by azaroth42** [comment]
I do, but you can't even add a second email address to your orcid record! Cue Simeon ... PRs welcome ;)

**Comment by zimeon** [comment]
We could simply say that each editor gets to link their name (bolded) to whichever site they prefer, an ORCID by default but if Rob want to link to his own page instead then that seems OK too.

**Comment by azaroth42** [comment]
Is there an orcid icon we could use instead of the meaningless number?

**Comment by azaroth42** [comment]
This: ?

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
OK, so how about the following:

  * **[Michael Appleby](http://orcid.org/0000-0002-1266-298X)** [ORCID iD.gif)](http://orcid.org/0000-0002-1266-298X), _[Yale University](http://www.yale.edu/)_
  * **[Robert Sanderson](http://www.stanford.edu/~azaroth/)** [ORCID iD.gif)](http://orcid.org/0000-0003-4441-6852), _[Stanford University](http://www.stanford.edu/)_
  * **[Stuart Snydman](https://profiles.stanford.edu/stuart-snydman)**, _[Stanford University](http://www.stanford.edu/)_

where the rules are:

  * Editor chooses link on name but all have them to avoid it looking odd with some linked and some not, I choose to have ORCID on mine and Rob chooses to have his Stanford page. Name bolded (I don't know what Stu wants his name to link to but just put his Stanford profile for want of something better)
  * If there is an ORCID, we display the ORCID icon and link to that
  * Organization linked and in italics

**Comment by jpstroop** [comment]
I'm fine with that

**Comment by azaroth42** [comment]
:+1: Looks good to me!

**Comment by mikeapp** [comment]
+1, looks much better than displaying the IDs

**Comment by zimeon** [comment]
Expect new commit later this evening...

**Comment by zimeon** [comment]
OK, made changes as above and rebased to clean commit history. <http://674_orcid_for_editors.iiif.io/api/annex/notes/editors/> etc. does not seem to show changes, not sure what current setup is (and whether I should not have rebased). Checked all affected pages on my local machine.

**Comment by azaroth42** [comment]
Deployed to http://674_orcid_for_editors.iiif.io/api/annex/notes/editors/ (etc) and bit :+1: from me!

**Comment by jpstroop** [comment]
So linky, much web, VERY GREEN. I removed the underscores just for the editors names to help further remove clutter. 

Before:
image

Now: http://674_orcid_for_editors.iiif.io/api/presentation/2.0/

**Comment by zimeon** [comment]
:+1: to removing the underlines

**Comment by azaroth42** [comment]
:+1: very appreciation much thankful

**Comment by mikeapp** [comment]
:+1: much improved!

**Pull request merged**
