### PR TITLE
Use rightsstatements.org examples

### LINKED ISSUE #1094: Use rightsstatements.org for license/rights examples in Image API
Clone of #960 to separate Image API case from Presentation API  case. We agreed that we should use examples from rightsstatements.org as these are likely good statements for our community. In Image API 2.1 we have two examples that include `license` (to be renamed `rights` in v3 #644):

  * http://iiif.io/api/image/2.1/#rights-and-licensing-properties -- example currently has `"http://example.org/rights/license1.html"`
  * http://iiif.io/api/image/2.1/#complete-response -- example currently has `[ "http://example.org/rights/license1.html", "https://creativecommons.org/licenses/by/4.0/" ]`

Tasks:
 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

### PR DESCRIPTION
**Pull request by zimeon**
Fixes #1094

### CODE REVIEW

**Comment by azaroth42** [comment]
:+1:

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
@tomcrane? @mikeapp?

**Comment by tomcrane** [comment]
👍 (merge on 4?)

**Comment by mikeapp** [comment]
👍

**Pull request merged**
