### PR TITLE
Add sizeAboveFull DOS warning. 

### LINKED ISSUE #683: sizeAboveFull is a security risk
See this PR on Loris: https://github.com/loris-imageserver/loris/pull/199

As I said there, the new max stuff addresses this from one angle, but we should probably surface the security risk either in [section 10](http://iiif.io/api/image/2.1/#security-considerations) and/or where `sizeAboveFull` is explained.

### PR DESCRIPTION
**Pull request by jpstroop**
Closes #683.

Would be here: http://dos_warning.iiif.io/api/image/2.1/

### CODE REVIEW

**Comment by azaroth42** [comment]
Auto-deploy fixed.  Text now at http://dos_warning.iiif.io/api/image/2.1/#security-considerations

:+1: from me.

Maybe consider RECOMMENDED ? There's some other RFC words in that section.

**Comment by jpstroop** [comment]
I think we should limit RFC keywords to normative sections. You can expose
yourself to DOS attacks if you want, your server will still work (until it
doesn't, but that's not our problem).

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by zimeon** [comment]
I agree with @jpstroop, best to strip RFC keywords out of non-normative sections (10. and 11. at least)

**Comment by jpstroop** [comment]
Took them out of 10 and 11.

**Comment by azaroth42** [comment]
:+1:

**Comment by mikeapp** [comment]
:+1:

**Comment by tomcrane** [comment]
:+1:

**Comment by zimeon** [comment]
:+1: (to source of 5eb3be3 even if auto-site not happen)

**Comment by jpstroop** [comment]
Rebased against master so cap will work

**Comment by jpstroop** [comment]
This has ample :+1: s to merge when someone feels motivated

**Pull request merged**
