### PR TITLE
Clarify type

### LINKED ISSUE #815: Clarify @type requirement only for main resource classes
and not things like Service, Thumbnail and what have you.

Eds agree (4/22 call)

cc @regisrob

### PR DESCRIPTION
**Pull request by azaroth42**
Add a note to the "All ... MUST ..." under @type to clarify what all is being described.

http://clarify_type.iiif.io/api/presentation/2.1/#type

Closes #815.

### CODE REVIEW

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
:+1: to content but a question on style: This would add a second "_N.B._" to the document, do we want that? Would it be clearer to instead stick with the more frequent use of "Note...", perhaps even "Note well.." as we have already one other place.

**Comment by tomcrane** [comment]
:+1:  Given that these two sections are short and the NB is short, I think it would read fine without either NB or Note, just

This requirement applies....

This PR (and #820) need to be merged before announcing spec freeze I assume?

**Comment by mikeapp** [comment]
:+1:

**Comment by zimeon** [comment]
:+1: to "This requirement applies...."

**Comment by azaroth42** [comment]
I think a green Note block would be overkill for this. Removing both NBs.

**Comment by zimeon** [comment]
:+1: - CI issue is just the old link problem with Rob's homepage, will go away with merge

**Pull request merged**
