### PR TITLE
letter to dams

### PR DESCRIPTION
**Pull request by srabun**
letter to DAMS: http://dams_letter.iiif.io/news/2017/05/01/letter-to-dams/

### CODE REVIEW

**Comment by azaroth42** [comment]
On the museum call today there was discussion about the ordering of the names.  Currently they're simply chronological with us first, and the most recent signer last.  That's not ideal -- could we alphabetize them, and add the location of each museum more consistently after the name?

(@mikeapp)

**Comment by azaroth42** [comment]
:+1:

**Comment by srabun** [comment]
thanks @azaroth42 ! @mikeapp

**Comment by mikeapp** [comment]
👍

**Pull request merged**
