### PR TITLE
Add NYC event and event index

### PR DESCRIPTION
**Pull request by azaroth42**

### CODE REVIEW

**Comment by azaroth42** [comment]
Links:
 * http://nyc.iiif.io/event/
 * http://nyc.iiif.io/event/newyork/

**Comment by tomcrane** [comment]
+1 

link is http://nyc.iiif.io/event/2016/newyork/ rather than the one you gave above but the link from /event/  is correct.

Obviously the Eventbrite links don't go to a real event, but I didn't spot anything else on a read through.

**Comment by jpstroop** [comment]
I'm not huge fan of "IIIF and its Benefits" -- I feel like it could be stronger.

 * Benefits of IIIF
 * IIIF Up and Running
 * IIIF Community Introduction
 * IIIF: A Web-Based Approach to Image Interoperability

...

**Comment by azaroth42** [comment]
Thanks @tomcrane, thinko'd the link.
@jpstroop Agree. I took the name from @tomcramer's email to iiif-discuss. I (personally) hadn't been mentally distinguishing the different events of the week.

Advantages of IIIF and its Community ?  (Community Benefits sounds very HR)

**Comment by jpstroop** [comment]
I was really kind of proud of _IIIF Up and Running_, but I'm not going to quibble.

**Comment by jpstroop** [comment]
:+1:

**Comment by tomcramer** [comment]
I would like to refine the framing for all three events. The Save the Date email text was OK for a stop gap, but we will need better text for the web and email invites.

- Tom




On Feb 18, 2016, at 1:52 PM, Rob Sanderson <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @tomcrane<https://github.com/tomcrane>, thinko'd the link.
@jpstroop<https://github.com/jpstroop> Agree. I took the name from @tomcramer<https://github.com/tomcramer>'s email to iiif-discuss. I (personally) hadn't been mentally distinguishing the different events of the week.

Advantages of IIIF and its Community ? (Community Benefits sounds very HR)

**Comment by azaroth42** [comment]
@tomcramer Can we ship it and refine later (say next Monday?) or want to hold off on publishing?
Eventbrites are also up (see links in the page)

**Comment by tomcramer** [comment]
ok to publish as is, but lets refine before we start doing email blasts.
Thx!
- Tom

**Comment by zimeon** [comment]
Belated :+1: on http://nyc.iiif.io/event/2016/newyork/

**Pull request merged**
