### PR TITLE
add links include

### PR DESCRIPTION
**Pull request by jpstroop**
Proposal. Now that the site has been pared down, centrally manage links in an include? I have constantly having to scroll to the bottom.

### CODE REVIEW

**Comment by jpstroop** [comment]
This builds and works just fine locally...does it work for others?

**Comment by tomcrane** [comment]
:+1: works for me

**Comment by azaroth42** [comment]
Yup :+1:

**Comment by jpstroop** [comment]
Do not merge yet...needs a refactor.

**Comment by jpstroop** [comment]
Oh, haha. I'll make another PR to clean up the code.

**Pull request merged**
