### PR TITLE
Re-structure presentation API doc; closes #723

### LINKED ISSUE #723: "Figure 3. All Resource Types"
Where are figures 1 & 2?

### PR DESCRIPTION
**Pull request by azaroth42**
Overkill on closing #723
http://prezi_refactor.iiif.io/api/presentation/2.1/

### CODE REVIEW

**Comment by jpstroop** [comment]
This is basically the outline we were discussing on slack, and I like it. Some nitty-gritty:

 * [ ] [contentLayer](http://prezi_refactor.iiif.io/api/presentation/2.1/#contentlayer) has _Usage:_ above the bullets. None of the other terms do.
 * [ ] The use of bullets in [Section 3](http://prezi_refactor.iiif.io/api/presentation/2.1/#resource-properties) seems a little sporadic. I propose we use bullets exclusively for the normative/RFC statements, and move anything that is not RFCish into the preceeding prose. And the inverse: take any RFC normative/RFC statements out of the prose and make them bullets.
 * [ ] Somewhat related to the previous point, [viewingHint](http://prezi_refactor.iiif.io/api/presentation/2.1/#viewinghint) and [viewingDirection](http://prezi_refactor.iiif.io/api/presentation/2.1/#viewingdirection) have two bulleted lists: one that lists the possible values, and one for the RFC points. I think they're separate `ul`s, but visually they run together. Could we come with some styling that makes the supported values distinct? Maybe they should be linkable too (`h6`)?
 * [ ] Just CSS: The spacing in [Section 2](http://prezi_refactor.iiif.io/api/presentation/2.1/#resource-type-overview) (in particular) gets tight. I wonder if we could try removing the left margin applied to the text under the `h5`s (they were `dl`s until early last week).
 * :+1: to collapsing the `members` examples into the existing `ranges`/`canvases` and `collections`/`manifests` examples
 * [ ] Examples are bulleted for [Segements](http://prezi_refactor.iiif.io/api/presentation/2.1/#segments) and nowhere else that I can see.
 * [ ] Let's see if we can override the HTML `id`s in [Section 2](http://prezi_refactor.iiif.io/api/presentation/2.1/#resource-type-overview) to, e.g. `#manifest-overview`, so that Manifest (currently [5.1](http://prezi_refactor.iiif.io/api/presentation/2.1/#manifest-1)) can be `#manifest` instead of `#manifest-1`.
 * [ ] Should Section 2 contain forward references to the detailed description in Section 5?

**Comment by jpstroop** [comment]
I should say, I'm happy to take a stab at any of this if you'd like. :hocho:

**Comment by azaroth42** [comment]
For the styling in Section 2 ... agree that it's messy. The float right only works for some screen widths, and the images overlap down into the following sections. What I'd like is what we would have used a table for in 1995 (when I learnt HTML) to make sure that everything stays in line.

I've done the other tasks, and redeployed.

**Comment by jpstroop** [comment]
Does getting rid of the left padding/margin really make that much difference wrt that responsive problem? I'd like to see [these lines](https://github.com/IIIF/iiif.io/blob/prezi_refactor/source/css/spec-doc2.scss#L109-L114) go from the CSS.

**Comment by azaroth42** [comment]
I've tried futzing around with the CSS here without success. Can we merge as is and fix the CSS later?

**Comment by azaroth42** [comment]
Closes #734 ; Closes #710 ; Closes #697 ; Closes #646 ; Closes #58

**Comment by jpstroop** [comment]
Talking of saving space over on #739, there a lot of properties in [Section 3](http://prezi_refactor.iiif.io/api/presentation/2.1/#resource-properties) that have a single bullet which, I think, could just as easily be the last sentence of the preceding paragraph.

**Comment by tomcrane** [comment]
http://prezi_refactor.iiif.io/api/presentation/2.1/#thumbnail has six statements about cardinality, whereas http://prezi_refactor.iiif.io/api/presentation/2.1/#attribution has just one - but I think the presentation should be the same in both cases even if it results in a dangling bullet. I _personally_ don't mind that at all in this context, although it annoys me in others!

**Comment by jpstroop** [comment]
A list of one thing...it just bugs me. I'm out of time for the moment, but what about:

__Cardinality:__ One constraint

__Cardinality:__
 * One constraint
 * Two constraint
 * Three constraint

**Comment by tomcrane** [comment]
Some of the bullets combine a statement about cardinality with some additional information that goes with it, e.g., "A content resource may have exactly one format, and if so, it must be the value of the Content-Type header returned when the resource is dereferenced." Which might make a "Cardinality:" prefix slightly misleading. We want those clauses to stay together, but it's not always just about cardinality.

**Comment by mikeapp** [comment]
For me, having consistency within the presentation of the properties helps, even if it results in lone  bullets.

**Comment by zimeon** [comment]
I'm with @tomcrane and @mikeapp ... consistent layout trumps lone bullet issues for me

**Comment by jpstroop** [comment]
OK, fine, but (one last try)--what is the consistency? Until the reader puts it together, it just looks like some RFC assertions are in paragraphs, and some are in bullets. Why? We just got sick of writing text? Maybe "Cardinality" isn't the right word. Maybe "Constraints"? We should explain the intent of those lists.

**Comment by zimeon** [comment]
I could see adding a word at the end of the paragraph before the bullets (could be "Constraints:") but the original argument for removing all the floating "Usage:" lines (#651) was that it was clutter that didn't help readability.

**Comment by jpstroop** [comment]
Bah, I missed #651! I would have argued against.

I think:

__Constraints:__ One constraint

__Constraints:__
 * One constraint
 * Two constraint
 * Three constraint

Would be better.

**Comment by zimeon** [comment]
Hmmm... I'm still very much in favor of #651, I think the 2.1 draft is better than 2.0 for layout.

**Comment by jpstroop** [comment]
Overall the layout is absolutely better. I just don't think the bullets makes sense. _gives up_

**Comment by azaroth42** [comment]
Given that we're failing in master and this fixes it, plus there's a lot of other branches ready to merge once this hits, can we hit the green button? :+1:s requested from @IIIF/editors

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
:+1:

**Comment by mikeapp** [comment]
:+1:

**Pull request merged**
