### PR TITLE
Update: Add DIAMM to organizations

### PR DESCRIPTION
**Pull request by ahankinson**
DIAMM will be publishing our image collection using IIIF.

### CODE REVIEW

**Comment by azaroth42** [comment]
:+1:

**Comment by ahankinson** [comment]
No problem.

**Comment by zimeon** [comment]
:+1:

**Comment by zimeon** [comment]
will postpone merge 'til end of day, just in case...

**Comment by jpstroop** [comment]
:+1: when ready

**Comment by ahankinson** [comment]
:fireworks: Thanks!

**Pull request merged**
