### PR TITLE
Link to MOU from editoral process

### LINKED ISSUE #865: Editorial doc should link to the MOU
Noted by @sdellis on iiif-discuss.

### PR DESCRIPTION
**Pull request by jpstroop**
Closes #865

### CODE REVIEW

**Comment by azaroth42** [comment]
:+1: assuming the travis failure is link checker related. Can we just disable it?

**Comment by jpstroop** [comment]
It wasn't because of a link check...seems like htmllint found something new to complain about.  Hopefully the latest commit fixes it.

**Comment by jpstroop** [comment]
Also, I'm :-1: on removing the link check. I'd rather correct or remove the bad links.

**Comment by jpstroop** [comment]
OK. Includes updated and rebased.

**Pull request merged**
