### PR TITLE
Update code of conduct to cover all interactions

### LINKED ISSUE #847: Update code of conduct to cover all interactions
Be they in person at events, online in slack or via email.

Tagging this as normative given the "rules" nature of the change... but social rather than technical.

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #847

### CODE REVIEW

**Comment by jpstroop** [comment]
👍

**Comment by tomcrane** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Comment by zimeon** [comment]
I think it needs a bit more work, had put some comments in #847 a few days ago

**Comment by zimeon** [comment]
:+1:, thanks

**Comment by mikeapp** [comment]
👍 for the changes

**Pull request merged**
