### PR TITLE
Prezi issues

### LINKED ISSUE #610: Clarify non text/plain formats okay for annotations
The only format mentioned in the spec is text/plain. It should be clearer that this is not a requirement, and text/html text/markdown or any other is possible. A recommendation for text/plain or text/html might be useful, however?

From: https://github.com/IIIF/mirador/issues/585

### LINKED ISSUE #611: Hotspot linking
A use case from National Library of Norway: There are areas in the canvas that should be linked to either other canvases or external documents.  For example, linking from "continued on page 5" to the region on page 5 where the article is continued, or linking a reference to something to a description of it.

Open Annotation has a "linking" motivation that seems appropriate and could be added as a subsection in section 6 of prezi/2.1

```
{
  "@id":"http://www.example.org/iiif/book1/annotation/anno1",
  "@type":"oa:Annotation",
  "motivation":"oa:linking",
  "resource": {
    "@id":"http://www.example.org/page-to-go-to.html",
    "@type":"dctypes:Text",
    "format":"text/html"
  },
  "on":"http://www.example.org/iiif/book1/canvas/p1#xywh=500,500,150,30"
}
```

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #611 ; Closes #610

### CODE REVIEW

**Comment by jpstroop** [comment]
I think there are sufficient :+1:s from @mikeapp, @zimeon, and me in the issues. :ok_hand: :question:

**Comment by jpstroop** [comment]
Can I get one more +1 to merge?

**Comment by jpstroop** [comment]
@IIIF/editors can we get +1s or comments on the two open PRs before the meeting tomorrow?

**Comment by jpstroop** [comment]
This is going stale...

**Comment by zimeon** [comment]
:+1:

**Comment by jpstroop** [comment]
@azaroth42 I think this is one of the branches that had it's history rewritten following mergegate? I'll merge if you want, but you should be on hand in case the site breaks.

**Comment by mikeapp** [comment]
:+1:

**Comment by jpstroop** [comment]
Seems to have gone :ok:

**Pull request merged**
