### PR TITLE
Add graffle, update object diagram

### LINKED ISSUE #781: All resource types diagram missing arrow for Range
on the ranges can include ranges arrow.

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #781

### CODE REVIEW

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
The new png is much bigger (W: 523px | H: 874px  vs  W: 348px | H: 583px). Is that intentional?

**Comment by azaroth42** [comment]
No, sorry! Will regenerate at lower DPI.

**Comment by mikeapp** [comment]
:+1:

**Comment by zimeon** [comment]
:+1: (non-normative so will merge)

**Pull request merged**
