### PR TITLE
Image 2.1 Branch Rebased

### PR DESCRIPTION
**Pull request by jpstroop**
This is a merge-able version of the image-21 branch, rebased against master and squashed into logical commits. ~~Note that the css for the alerts won't look correct until merged;~~ I *think* everything else is good. :fire: at will.

### CODE REVIEW

**Comment by jpstroop** [comment]
Following the merge, the image-21 branch should be deleted (and any others no longer in use). We can start image-21-4 (i.e. draft 4) if necessary.

**Comment by jpstroop** [comment]
PS: I forced an update to this branch, so the subdomain preview is probably borked. :sunglasses:

**Comment by jpstroop** [comment]
:rose: :tulip: :turtle: :tumbleweed: ...

**Comment by azaroth42** [comment]
:+1: from me. Can fix any minor issues later.

**Pull request merged**
