### PR TITLE
631 ontology

### LINKED ISSUE #523: Create Image Ontology with iiif:Size and iiif:Tile classes
So as to avoid unclassed blank nodes in the RDF view of the content.

### LINKED ISSUE #551: Update prezi ontology
Ontology.xml is out of date and needs some attention.

### LINKED ISSUE #623: iiif:Image or not?
http://iiif.io/api/image/2/info_frame.json shows `"@type": "iiif:Image"`.
However, the table at the beginning of http://iiif.io/api/image/2.0/#image-information  and the example at the end of this section don't show such type in the response.
Should there be such type or not? I'm working on mapping Getty CONA images to RDF thereon IIIF and will appreciate a quick answer very much :-)

### LINKED ISSUE #631: image vs image-info URL and type
#623 wonders whether `{scheme}://{server}{/prefix}/{identifier}/info.json` should return `"@type": "iiif:Image"` or not.
This issue wonders whether there should be 1 or 2 URLs, what should be the link between them, and how the statements should be distributed between them.
I'm mapping Getty CONA images. Assume that http://cona-images.getty.edu/iiif/ is an IIIF server. Currently I've made these statements (in turtle):
```turtle
<http://cona-images.getty.edu/iiif/12345> 
  ### "free" description (DC/DCT/DCTypes)
  a dctype:StillImage;
  dc:identifier "12345";
  dc:title "View of St Peters basilica at sunset";
  dc:description "The dome practically shines";
  dc:rights "(C) Getty Museum, photography John Smith";
  ### IIIF description
  a iiif:Image;
  exif:height 4000;
  exif:width 6000;
  doap:implements <http://iiif.io/api/image>;
  dct:conformsTo <http://iiif.io/api/image/2/level0.json> .
```
I'm happy with this but http://iiif.io/api/image/2.0/#image-information requires the latter group of statements to be returned by http://cona-images.getty.edu/iiif/12345/info.json. The question is, should they also be also *attached* to such URL? CoolURIs says "don't use extension in semantic URLs", and it's good to link the two nodes with a relation, so it becomes eg:
```turtle
<http://cona-images.getty.edu/iiif/12345> 
  a dctype:StillImage, iiif:Image;
  dc:identifier "12345";
  dc:title "View of St Peters basilica at sunset";
  dc:description "The dome practically shines";
  dc:rights "(C) Getty Museum, photography John Smith";
  wdrs:describedby <http://cona-images.getty.edu/iiif/12345/info>.

<http://cona-images.getty.edu/iiif/12345/info>
  a iiif:ImageInfo;
  exif:height 4000;
  exif:width 6000;
  doap:implements <http://iiif.io/api/image>;
  dct:conformsTo <http://iiif.io/api/image/2/level0.json> .
```
I'm not fond of complexity: neither wdrs:describedby, nor using two types `iiif:Image` vs `iiif:ImageInfo`, nor using two nodes... I'd be happier to stick with the first (simple) variant.

But is it ok if http://cona-images.getty.edu/iiif/12345/info.json returns statements about http://cona-images.getty.edu/iiif/12345 ?

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #631, Closes #551; Closes #523. Properly re-closes #623.

### CODE REVIEW

**Comment by azaroth42** [comment]
Note the additions to image/2.1/ to optionally allow @type on any resource.

**Comment by zimeon** [comment]
@azaroth42 - I suppose all the python code is stuff you've been developing for some time to manage the Shared Canvas model. Should Zone be entirely chopped/commented out for IIIF?

**Comment by jpstroop** [comment]
I don't mind it as-is (with the comment "...Note that Zones are not currently used in the IIIF Presentation API")

**Comment by zimeon** [comment]
OK, not really too fussed about Zone. :+1:

**Comment by jpstroop** [comment]
:+1:

**Comment by jpstroop** [comment]
Do we consider this normative, or can we merge?

**Comment by jpstroop** [comment]
@tomcrane @mikeapp ?

**Comment by mikeapp** [comment]
:+1:

**Pull request merged**
