### PR TITLE
Prep for 2.1 image/prezi, and 1.0 search release

### PR DESCRIPTION
**Pull request by zimeon**
Updates that will be required for new releases. Obviously all pending review in the afternoon session today...

### CODE REVIEW

**Comment by jpstroop** [comment]
closes #833

**Comment by azaroth42** [comment]
A most emphatic :+1:

**Comment by zimeon** [comment]
:+1:

**Comment by tomcrane** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Pull request merged**
