### PR TITLE
Clarify SpecRes, Choice for image annos

### LINKED ISSUE #816: Image annotations could be oa:SpecificResource
http://iiif.io/api/presentation/2.1/#image-resources suggests that the annotation resource '**SHOULD** have an @type of “dctypes:Image”'

One reasonable exception to this is where the image annotations are of @type `oa:SpecificResource` - e.g., to crop out scanner machinery. The spec should warn that some clients might not be able to cope with this (it has to handle the crop).

### PR DESCRIPTION
**Pull request by azaroth42**
http://specific_image.iiif.io/api/presentation/2.1/#image-resources

Add note that just because it SHOULD be an image, doesn't mean that it always will be one, and there are lots of valid situations to test for.

Closes #816

### CODE REVIEW

**Comment by tomcrane** [comment]
:+1:

**Comment by zimeon** [comment]
:+1:

**Comment by jpstroop** [comment]
👍

**Comment by mikeapp** [comment]
:+1:

**Comment by azaroth42** [comment]
Jon, can you please deploy master... I don't have a laptop yet, let alone
cap installed!

Thanks!

R

**Pull request merged**
