### PR TITLE
Add `max` size keyword, deprecate `full` size keyword

### LINKED ISSUE #663: When we have maxWidth/maxHeight/maxArea, should there be a way to ask for the largest size for a given region?
Separating this from #620, comments so far:

@tomcrane wrote: Given the discussion on what this issue means a server should do in response to a size parameter that it can't support, is there an argument for an additional size parameter "best" (or similar)? `/full/best/0/default.jpg` or `/100,100,10000,10000/best/0/default.jpg`.  This would have definite utility - the UV offers a "download high res" option that currently requires out of band knowledge of the server's abilities - all a viewer need do is ask for `/full/best/`... (or "max")

@azaroth42 wrote: Or ... "default" :wink:

@glenrobson wrote: Regarding @tomcrane comment on `/full/best/0/default.jpg` I would like to be able to support a URL that will blindly get the best image I can provide without working it out from the info.json. I thought it may be required for the EDM Web Resource id but in the end we used the thumbnail URL. It still may come up that someone would want to use this URL. ... For public domain images I would probably look at disabling the maxwidth/area restriction for these. I'm not sure how the discussions will go but it could be that we don't give the full resolution for these images and so a `/full/best/0/default.jpg` would be useful.

@mattmcgrattan wrote: +1 for a 'best' option.

@mikeapp wrote: best or max could return a size anywhere from `/full/` down to the tile size on the long edge, its going to be difficult to use in a consistent way. Would it be OK if the user clicked 'download high res' and got a 350x512 image? I think you'd need to check the info.json and not offer the option if the server doesn't support a reasonably high resolution download. Also, if someone codes a client to display images using /best/ in order to work around tile size limitations, it could have unfortunate consequences when hitting a server that can return a full-scale image. Given the proposed size restrictions I'd really like the option to indicate that I'll accept a smaller size, e.g., `/0,0,2000,2000/<1000,/` for 'up to 1000 wide' when creating links without loading info.json. But that would add even more complexity on the server side :frowning:

### PR DESCRIPTION
**Pull request by jpstroop**
:arrow_up: that. Advances #678, closes #663.

Seems like the deploy script is broken. Changes would be [visible here](http://mad_max.iiif.io/api/image/2.1/#size).

### CODE REVIEW

**Comment by azaroth42** [comment]
I would prefer a warning slightly less definite in case we change our minds. Something like:

The size keyword `full` is likely to be removed in favor of only supporting `max` in Version 3.0 and thus should be considered as deprecated.

And we might want to define deprecated in our semantic versioning doc?

**Comment by jpstroop** [comment]
I'd rather speak with a little more conviction. What do you think the of [this revision](http://mad_max.iiif.io/api/image/2.1/#full-dep)?

**Comment by tomcrane** [comment]
I like that revision.

**Comment by azaroth42** [comment]
I'm good with the revision, though maybe there's a meta point we can discuss about whether all such deprecations are signaled.  Will raise an issue

**Comment by azaroth42** [comment]
To be clear:  :+1:

**Comment by jpstroop** [comment]
Added another commit. What is the compliance level for `max` size? It will be 0 in 3.0, but until then? 

New features aren't breaking changes, so it's up to us. That said, I don't think we should raise the bar for getting to 2.1 too much, so I'd say either level 2 or completely optional, with a slight leaning toward level 2. This commit has it marked as completely optional which seemed safest.

**Comment by azaroth42** [comment]
I have cold feet with all of the example changes.
--> issue

**Comment by jpstroop** [comment]
@azaroth42 This is rebased against master and just waiting for an image that demonstrates `max` size.

**Comment by jpstroop** [comment]
:+1: (it looks like the merge might be messy)

**Comment by azaroth42** [comment]
:+1: to merge, needs everyone please. @zimeon @tomcrane @mikeapp

**Comment by zimeon** [comment]
:+1:

**Comment by mikeapp** [comment]
:+1:

**Comment by azaroth42** [comment]
Rebased to allow merge.

**Comment by jpstroop** [comment]
Hah, forgot it was my PR. I guess @azaroth42 and I should recuse ourselves. @tomcrane @zimeon @mikeapp ?

**Comment by zimeon** [comment]
I'm still :+1:

**Comment by jpstroop** [comment]
Various iterations have been :+1: by everyone, and the changes since have been non-normative examples. Pull the trigger?

**Pull request merged**
