### PR TITLE
update to point to iiif-av & small changes to community page

### PR DESCRIPTION
**Pull request by jronallo**

### CODE REVIEW

**Comment by azaroth42** [comment]
Can we also fix the text to read:  Following a workshop hosted by the British Library

Otherwise, :+1: from me!

**Comment by zimeon** [comment]
Changes with @azaroth42's tweak look good. +1

**Comment by jpstroop** [comment]
:+1:

**Comment by jronallo** [comment]
Only text fix I made with the initial commit was to remove a line break on the text. I've submitted another commit to improve the text now.

**Comment by jronallo** [comment]
Failures are all external link failures, but nothing near what I touched with these commits.

**Pull request merged**
