### PR TITLE
Tsg decisions

### PR DESCRIPTION
**Pull request by srabun**
Added the section that addresses decision making in Tech Spec groups: http://tsg_decisions.iiif.io/api/annex/notes/editors/#status-of-this-document

### CODE REVIEW

**Comment by sdellis** [comment]
This is related to #1041, so I think that merging of this change should wait until after today's community discussion about design principles takes place .

**Comment by zimeon** [comment]
Oh, actually, this is a dated document -- we should collect together all the changes we intend to make (including the reworking on sections 1 and 2) into one before merging and pushing out complete with log entry

**Comment by azaroth42** [comment]
Good to change design principles --> design patterns

**Comment by srabun** [comment]
@zimeon @azaroth42 all changes from [doc](https://docs.google.com/document/d/1gDLZt7ZqAoN87__XBC53hpqxLMfSsFgMugoG6nkvGqU/edit?usp=sharing) now incorporated

**Comment by azaroth42** [comment]
:+1: from me. @jpstroop @mikeapp @tomcrane ?

**Comment by azaroth42** [comment]
Oh, needs a changelog entry before merging please.

**Comment by mikeapp** [comment]
👍

**Comment by jpstroop** [comment]
👍

**Comment by zimeon** [comment]
:+1: after making changelog latest first

**Comment by zimeon** [comment]
Given that I made the last change, there should be one more sanity check before merge....

**Comment by srabun** [comment]
Change log order noted for future reference. Looks good to me @zimeon

**Comment by tomcrane** [comment]
👍 and will merge

**Pull request merged**
