### PR TITLE
update hash fragment when we scroll

### PR DESCRIPTION
**Pull request by jpstroop**
I don't really know if I like this, but here it is, for @zimeon

### CODE REVIEW

**Comment by azaroth42** [comment]
:+1:

**Comment by jpstroop** [comment]
moma.org is down

**Comment by jpstroop** [comment]
Branch: http://hash_scroll_update.iiif.io/api/presentation/2.1/

**Comment by zimeon** [comment]
:+1:

**Comment by mikeapp** [comment]
:+1:

**Comment by azaroth42** [comment]
Change to :-1: as it messes up browser history :(

**Comment by zimeon** [comment]
This feature on https://developers.google.com/youtube/iframe_api_reference does not seem to mess up the history (back button function). :-1: until that resolved

**Comment by jpstroop** [comment]
I think I might know how to fix the history and will look next week. Agree
:-1: until fixed.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by jpstroop** [comment]
OK, @IIIF/editors,  back button is working as expected.

Note that the hashes URIs are still in the history, and I'm not sure how to fix that without going much deeper:

screenshot from 2016-04-10 06-57-46

But I don't think that's really a concern, is it?

**Comment by azaroth42** [comment]
Yep :+1: from me now!

**Comment by zimeon** [comment]
:+1: (history seems good now, checked on chrome & firefox)

**Comment by jpstroop** [comment]
I'm OK with this; I'm still not sure I like it, but if everyone else is +1, I'm OK with keeping it.

**Comment by azaroth42** [comment]
@tomcrane @mikeapp ? If you're okay, go ahead and merge

**Comment by mikeapp** [comment]
:+1: Looks good on Safari, Chrome, Firefox on Mac.

**Pull request merged**
