### PR TITLE
[DO NOT MERGE] Image 21

### PR DESCRIPTION
**Pull request by jpstroop**
For real this time... _In theory_ nothing here should break existing specs, and at this point it seems odd to be pointing an increasing number of people to a branch. 

Better, I think, to merge this in, and add the w3c-style WIP warning at the top, [similar to what we've done with auth](http://iiif.io/api/auth/0.9/).

If we get a quorum of :+1:s I volunteer to do the merge / rebase and add the warning.

### CODE REVIEW

**Comment by zimeon** [comment]
I agree that as soon as we have draft/beta versions that get announced on iiif-discusss for general comment, they should be up on the main site with the large beta warning (in the same way as [auth](http://iiif.io/api/auth/0.9/)). So :+1:

**Comment by jpstroop** [comment]
Any more :+1: s?

**Comment by azaroth42** [comment]
source/api/image/2.1/authentication.md and its referenced images should be
deleted, no?

**Comment by jpstroop** [comment]
Yup, that would be a part of the merge.

There are some other Image-21 branches (`-clean`, `-524`). Are those anything? Can they be wiped out?

**Comment by jpstroop** [comment]
Closing in favor of #576

**Pull request closed without merging**
