### PR TITLE
initial info about the vatican event

### PR DESCRIPTION
**Pull request by srabun**
Added initial very basic information about Vatican conference to refer people to for upcoming save the date announcement: http://vatican_info.iiif.io/event/2017/vatican/

Additional info to be added as planning unfolds - many details are still being confirmed...

### CODE REVIEW

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Comment by srabun** [comment]
Thanks all. @azaroth42 if agreeable, please merge so I can announce on the call tomorrow and send out a notice?

**Comment by azaroth42** [comment]
:+1: from me too, merging

**Pull request merged**
