### PR TITLE
A Triple Eye Eff

### LINKED ISSUE #772: A IIIF or An IIIF?
We should be consistent. Currently we have 15 "a IIIF" and 11 "an IIIF" in the site.

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #772. Adds pronounciation guide to main specifications, and standardises on "a IIIF" rather than "an IIIF"

http://a_iiif.iiif.io/

### CODE REVIEW

**Comment by zimeon** [comment]
:+1:

**Comment by jpstroop** [comment]
:+1:

**Comment by tomcrane** [comment]
OK... :+1:

**Comment by mikeapp** [comment]
:+1: for consistency

**Pull request merged**
