### PR TITLE
Clarify availability of width and height

### LINKED ISSUE #477: Clarify and width and height are for calculating an aspect ratio only
`width` and `height` and `sizes : [ ]` are redundant.

Should we clarify the use of `width` and `height` as an aspect ratio by renaming to something like `aspect_x`, `asepect_y`. Or maybe even reduce to a single property, `aspect: { " x" : 123, "y" : 456 }`?

size comes from `sizes`.

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

### PR DESCRIPTION
**Pull request by jpstroop**
Closes #477

### CODE REVIEW

**Comment by jpstroop** [comment]
Yup sorry...that's what I get for doing this in a meeting...hang tight.

**Comment by jpstroop** [comment]
There. Now nothing is important.

**Comment by jpstroop** [comment]
Sure.

**Comment by mikeapp** [comment]
👍

**Comment by azaroth42** [comment]
:+1: but no merge due to 2.1.1

**Comment by jpstroop** [comment]
@azaroth42 PR is against the `image_211` branch. There is a `prezi_211` branch as all, and all of these PRs are against those. Then we can update in two big merges when we're ready.

**Comment by jpstroop** [comment]
There are already WIP PRs for those branches as well. (#979 and #978)

**Comment by azaroth42** [comment]
Doh! Sorry, my bad!  Merging on 4.

**Pull request merged**
