### PR TITLE
Add Universal Viewer event to Ghent for Friday

### PR DESCRIPTION
**Pull request by tomcrane**
There is no Eventbrite mini-event for this. I'm not sure if there needs to be or if it's part of the Unconference.

### CODE REVIEW

**Comment by azaroth42** [comment]
Let's make a mini-event for it. Not sure what will happen with people who have already registered tho? I guess they can make changes?  Should we wait to merge for that update?

**Comment by tomcrane** [comment]
Can we synchronise (ish) merging/depolying with updating the EventBrite listing? Is that possible? I guess the eventBrite should be live before this PR.

**Comment by zimeon** [comment]
It seems that this is not listed in the eventbrite https://iiif-winter-2015.eventbrite.com/ so shouldn't merge yet. Who is on the hook for the eventbrite update??

**Comment by blalbrit** [comment]
Eventbrite is updated. Please confirm that it looks good and then merge away.

**Comment by zimeon** [comment]
There is no "more info" link on the UV entry on the eventbrite menu but that isn't a showstopper. The details are still there lower on the page. Will merge.

**Comment by zimeon** [comment]
Looks good: <http://iiif.io/event/2015/ghent.html#universal-viewer-and-manifesto>

**Comment by blalbrit** [comment]
Thanks for catching that "more info" bit - fixed.

**Comment by zimeon** [comment]
'tis beautiful @blalbrit . All done I think.

**Pull request merged**
