### PR TITLE
exclude previous specs from sitemap

### PR DESCRIPTION
**Pull request by jpstroop**
Updates sitemap and robots.txt. We should merge and ping the Google. 👀

### CODE REVIEW

**Comment by jpstroop** [comment]
Hold off...@zimeon things we should have the disallows in the robots.txt.

**Comment by jpstroop** [comment]
OK, ready

**Comment by azaroth42** [comment]
:+1:

**Comment by mikeapp** [comment]
:+1:

**Comment by jpstroop** [comment]
Not normative, so I think we're good. @zimeon or @tomcrane care to merge?

**Comment by zimeon** [comment]
:+1: will merge

**Pull request merged**
