### PR TITLE
try adding calendar to community groups page

### PR DESCRIPTION
**Pull request by jpstroop**
Adds the calendar to the community page.

http://calendar.iiif.io/community/groups/

### CODE REVIEW

**Comment by zimeon** [comment]
:+1:

**Comment by azaroth42** [comment]
:+1: Merging on three eds for non normative website change.

**Comment by jpstroop** [comment]
Wait! let me tidy the css

**Comment by jpstroop** [comment]
OK. Assuming Travis is :green_apple:

**Pull request merged**
