### PR TITLE
added clarification in tsg formation and approval section

### PR DESCRIPTION
**Pull request by srabun**
Updated Group Framework page to clarify TSG discussions and TSG process for choosing group chairs, scheduling meetings, per: https://docs.google.com/document/d/1E1u82AiEbEfSqyrRvdMMywcbJSrWifZY7SPzaM5zigg/edit#

See: http://group_doc_update.iiif.io/community/groups/framework/#technical-specification-group-formation-and-approval

### CODE REVIEW

**Comment by azaroth42** [comment]
How about:

> within the community, as discussed on the IIIF-discuss mailing list.  If the discussion happens offline or in a smaller group, then summaries must be posted to solicit the input of the wider community.

**Comment by srabun** [comment]
@azaroth42 Yes, that's better wording.

**Comment by azaroth42** [comment]
:+1: from me

**Comment by zimeon** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Pull request merged**
