### PR TITLE
Image changelog for 2.1, fixes #614

### LINKED ISSUE #614: Change Log for Image API release
I can start to work on this while everyone else is en route to Ghent :cry:. For Image API so far I have:

 * Added `square` region
 * Removed recommend about JSON-LD context link header (I think--was it wrong)?
 * Added optional Rights and Licensing properties to info
 * Added a warning about inconsistency the sizes list and the canonical URI syntax
 * Misc editorial fixes and clarifications

### PR DESCRIPTION
**Pull request by zimeon**
Have taken what I think is a complete pass at the changelog for Image 2.1 based on @jpstroop's start. Needs attention from other eyes.

### CODE REVIEW

**Comment by jpstroop** [comment]
Deployed latest: http://image_changelog.iiif.io/api/image/2.1/change-log/

**Comment by zimeon** [comment]
:+1: to @azaroth42's changes. Have rebased against master but checks still fail because of proofer 500 recorded (?) for http://www.moma.org/ (which seems fine)

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
@mikeapp @tomcrane Either of you can merge :)

**Pull request merged**
