### PR TITLE
Add implementation note for slash parsing

### PR DESCRIPTION
**Pull request by azaroth42**
Rebased to new master

### CODE REVIEW

**Comment by azaroth42** [comment]
Any thoughts @jpstroop @zimeon @tomcrane @mikeapp ?

**Comment by azaroth42** [comment]
(New PR was from rebasing) @zimeon was in favor here: https://github.com/IIIF/iiif.io/pull/696#issuecomment-173717573

**Comment by jpstroop** [comment]
Propose this:

Server implementations may rely on frameworks that unescape the URI path, as is the case with the [Python Web Server Gateway Interface](https://www.python.org/dev/peps/pep-0333/). In such situations, request path for a given prefix can be parsed from the right in order to handle identifiers possibly containing slashes, given the knowledge of the API parameters and the prefix for which the server handles requests. Responses for missing identifiers containing slashes should result in a 404 response, rather than a 400 response for incorrect parameter values if this parsing approach is taken.

**Comment by jpstroop** [comment]
I'm not sure that I understand 

>  Responses for missing identifiers containing slashes may result in a 404 response, rather than a 400 response for incorrect parameter values if this parsing approach is taken.

Is this to account for the fact that it's still impossible to distinguish between a bad request (400) and a base URI that contains slashes and needs to be redirected to `/info.json`?

**Comment by sdellis** [comment]
I noticed from the link to #696 that it applies to the Image API and the server, but I have been wondering about client side parsing of IDs with slashes (it's helpful in many instances to use the shortened ID on the client rather than the full URI).  If there is a method for determining the ID (parsing from the right?) from the URI, it would be helpful to provide an example with this note.

**Comment by zimeon** [comment]
I'm not sure whether the 400/404 comment adds very much. In practice it doesn't seem to matter much as I don't imagine clients doing anything different for these different codes. I'm :+1: with the current PR but would also be fine removing the 400/404 sentence, or trying to clarify it with something more long-winded:

> If this parsing approach is used then the response code may be 404 in the case of a bad or missing identifier containing slashes, when it might otherwise be a 400 response if the path were parsed from the left.

**Comment by jpstroop** [comment]
I think we need to mention WSGI to make it clear why we're talking about this at all. I agree the 400/404 sentence could go.

At a minimum, the sentence that ends with "the prefix which the server handles requests for." needs to be fixed

**Comment by jpstroop** [comment]
:+1:

**Comment by mikeapp** [comment]
:+1:

**Comment by zimeon** [comment]
:+1:

**Pull request merged**
