### PR TITLE
Dependency updates and draft announcement, other tweaks

### PR DESCRIPTION
**Pull request by jpstroop**
OK @IIIF/editors...I sat down to draft an announcement this AM and couldn't get the site to build locally--it got away from me :wink: (please ignore #844 & #845). This PR does the following:

 * Updates jekyll and html-proofer gems
 * Adds link to Editorial Process from `/api/` page
 * Adds a draft announcement of new specs
 * Updates "Feedback Requested" text on `/api/` page

Too much at once, I realize, but nothing normative so hopefully 👌.

### CODE REVIEW

**Comment by jpstroop** [comment]
@IIIF/editors ping? Seems like we should get the specs announced.

**Comment by azaroth42** [comment]
Will try and look tomorrow!

**Comment by mikeapp** [comment]
The list of our names appears on a single line:
`The IIIF Editors Michael Appleby Tom Crane Robert Sanderson Jon Stroop Simeon Warner`

**Comment by zimeon** [comment]
I added punctuation to the author list (that seems better than making it long). I also changed to start with "We", IMO starting with "The IIIF Editors" seemed to make to much of us, we sign it anyway. Hope those are OK, :+1:

**Comment by mikeapp** [comment]
👍

**Comment by jpstroop** [comment]
👍

**Comment by azaroth42** [comment]
:+1: Merging...

**Pull request merged**
