### PR TITLE
Add a warning notice about prezi 3 status

### PR DESCRIPTION
**Pull request by tomcrane**

### CODE REVIEW

**Comment by jpstroop** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Comment by zimeon** [comment]
:+1: good to make this clear

**Comment by tomcrane** [comment]
(I can't deploy this to prezi3.iiif.io)

**Comment by jpstroop** [comment]
Great...for some reason I can't deploy now either. @srabun, when you get a moment, could you deploy the `prezi3` branch?

**Comment by srabun** [comment]
@jpstroop done

**Comment by tomcrane** [comment]
http://prezi3.iiif.io/api/presentation/3.0/ doesn't have the warning notice yet.

**Comment by jpstroop** [comment]
I moved some keys around and did it again. It took this time.

**Pull request merged**
