### PR TITLE
Use example rights URIs from CC and rightsstatements.org

### LINKED ISSUE #960: Use rightsstatements.org for license/rights examples in Presentation API
Along with creative commons to demonstrate that they both go in the same slot, and to hopefully promote usage.  Non normative ... 2.1.1 ?

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

### PR DESCRIPTION
**Pull request by zimeon**
Fixes #960

### CODE REVIEW

**Comment by jpstroop** [comment]
:+1:

**Comment by mikeapp** [comment]
👍

**Comment by jpstroop** [comment]
@azaroth42 or @tomcrane ?

**Comment by tomcrane** [comment]
👍

**Comment by azaroth42** [comment]
:+1:

**Comment by azaroth42** [comment]
But is 2.1.1 so not merging, right?

**Pull request merged**
