### PR TITLE
Stubs for groups

### LINKED ISSUE #647: Create Newspaper IG landing page
iiif.io/community/newspapers.md

Link to the folder of notes
Include the purpose bullet points

### PR DESCRIPTION
**Pull request by zimeon**
First stab at structure and stubs for community groups in IIIF, fixes #647

### CODE REVIEW

**Comment by zimeon** [comment]
CI errors are from HTML proofer in other parts of website:

```
- ./_site/event/2015/ghent-hotels/index.html
  *  External link http://www.accorhotels.com/ failed: 406 No error
- ./_site/model/shared-canvas/1.0/index.html
  *  External link http://dublincore.org/documents/dcmi-terms failed: got a time out (response code 301)
```

**Comment by azaroth42** [comment]
Deployed to http://community-groups.iiif.io/

**Comment by azaroth42** [comment]
:+1:

**Comment by jpstroop** [comment]
👍

**Pull request merged**
