### PR TITLE
Fix some minor typos

### PR DESCRIPTION
**Pull request by kinow**
Hi,

Had to read the presentation and search API's for a presentation and noticed a few typos here and there.

Not sure what is the policy for updating old/current specs. I can update the pull request in case only a subset of the changes are useful - if any at all :-)

Bruno

### CODE REVIEW

**Comment by zimeon** [comment]
Thanks @kinow . It is our usual policy to fix typos only in the unversioned documents and current versions (as patch release or next version), and to leave old versions archived. We also usually update one spec at a time so probably the best way forward will be for us to cherry-pick your commits -- I'll leave this PR open until we do that.

**Comment by kinow** [comment]
Thanks @zimeon . If anyone points which docs must be updated, I'd be happy to update the commits, rebase, and push-force.

**Comment by azaroth42** [comment]
@kinow Thank you so much for the very close reading and noting all the typos (mostly mine!)

The Annex documents and the Shared Canvas model document can be updated at will, but the api/SPEC/x.y/ documents should remain static.  I think the best course of action, is to take the api/ docs out of the PR and then accept it.

Then create an issue, tagged as milestone 2.2, with the typos to fix. 

Thoughts?

**Comment by kinow** [comment]
Sounds like a plan @azaroth42 ! Will update the pull request and, if I understand correctly, create an issue here in GitHub, letting someone else to tag it and link to this PR... or should I just update the PR and someone else will create the issue?

**Comment by kinow** [comment]
PR updated!

**Comment by azaroth42** [comment]
:+1: from me!

**Comment by azaroth42** [comment]
Merging! Thanks @kinow!

**Pull request merged**
