### PR TITLE
Fix fixtures, script, context, frame, add tests

### PR DESCRIPTION
**Pull request by azaroth42**
This adds checks for the manifest frame to the extent possible, based on the existing fixtures.
Also fixes the fixtures.

### CODE REVIEW

**Comment by azaroth42** [comment]
Ping?

**Comment by zimeon** [comment]
The changes look sensible. I note that when I run `build_prezi21_tests.py` manifests 6 and 64 are changed from the github version and don't pass `scripts/check_jsonld.py` -- is that intentional?

**Comment by azaroth42** [comment]
@zimeon Do you have the most recent iiif_prezi installed with the bug fixes that make 6 and 64 possible to build?

**Comment by zimeon** [comment]
@azaroth42 - I confirm that with the latest `iiif-prezi` I also get no changes to the fixture manifests on running `build_prezi21_tests.py` (except for 2 blank lines removed in 64), and that `scripts/check_jsonld.py` is happy.

**Pull request merged**
