### PR TITLE
Add impl consideration about directory traversal

### LINKED ISSUE #726: URI decoding identifiers is a security risk
I wonder if it bears mentioning in Security Considerations (section 10 of the Image API) that URI decoding of identifiers could open a server to directory traversal attacks in a naive file resolver that is just a path to the file and does not sufficiently sanitize the input?

So an identifier of "..%2F..%2F..%2F..%2Fpath%2Fto%2Fsystem%2Fimage.jp2" could be used to go fishing for images on the file system.

It could simply be this edit:
Applications must be careful to parse and sanitize incoming requests (URIs) in ways that avoid overflow, injection, and directory traversal attacks.

### PR DESCRIPTION
**Pull request by jpstroop**
Closes #726

### CODE REVIEW

**Comment by zimeon** [comment]
:+1:

**Comment by azaroth42** [comment]
:+1: non normative spec text

**Comment by mikeapp** [comment]
:+1:

**Comment by tomcrane** [comment]
:+1:

**Pull request merged**
