### PR TITLE
Clarify range's contentLayer, add example ; closes #707

### LINKED ISSUE #707: Range range contradiction
> Ranges _MAY_ include other ranges. This is done in a ranges property within the range. The values within the ranges list _MUST_ be strings giving the URIs of ranges in the list in the manifest.

> Ranges _MAY_ link to a layer...

### PR DESCRIPTION
**Pull request by azaroth42**
http://range707.iiif.io/api/presentation/2.1/#range

### CODE REVIEW

**Comment by jpstroop** [comment]
:+1:

**Comment by sdellis** [comment]
From the wording here, it seems permissible to have members, canvases, and ranges all present within the same range. Is this intended?

**Comment by azaroth42** [comment]
Yep, that's intentional :)

**Comment by zimeon** [comment]
:+1:

**Comment by mikeapp** [comment]
:+1:

**Comment by tomcrane** [comment]
:+1:

**Pull request merged**
