### PR TITLE
Changelog for Prezi

### PR DESCRIPTION
**Pull request by azaroth42**
Reviewable at: http://prezi_changelog.iiif.io/api/presentation/2.1/change-log/

### CODE REVIEW

**Comment by azaroth42** [comment]
:+1: to @jpstroop's tweaks

**Comment by jpstroop** [comment]
I'm :+1: overall as well.

**Comment by mikeapp** [comment]
:+1:

**Comment by zimeon** [comment]
:+1:, very nice and quite a sizable list

**Comment by jpstroop** [comment]
Non-normative, so we can merge at this point.

**Pull request merged**
