### PR TITLE
Blue/Green syntax, fix JSON examples

### PR DESCRIPTION
**Pull request by azaroth42**
Tweak new syntax highlighter styles to be less red and shouty. Fix some JSON errors in Presentation API revealed by new highlighter :)

Example:
  http://highlight-styles.iiif.io/api/presentation/2.1/#manifest-1

### CODE REVIEW

**Comment by jpstroop** [comment]
:+1:

**Comment by zimeon** [comment]
:+1: on the blue/green

And a commit with some more fixes and a checking script -- I haven't hooked the checking script up to the CI stuff but it is designed to run with exit(0) of OK, exit(1) if bad (plus msg). If I put the error back into `source/api/annex/services/index.md` we get:

```
simeon@Cider iiif.io>git diff source/api/annex/services/index.md 
diff --git a/source/api/annex/services/index.md b/source/api/annex/services/index.md
index 9355ba6..27dd00b 100644
--- a/source/api/annex/services/index.md
+++ b/source/api/annex/services/index.md
@@ -113,7 +113,7 @@ The service _MAY_ have additional information embedded from the Image Informatio
             "canonicalLinkHeader", "rotationArbitrary", "http://example.com/feature"
         ]
       }
-    ]
+    ],
   }
 }
simeon@Cider iiif.io>scripts/check_json.py
source/api/annex/services/index.md: bad JSON starting at line 91
==> Expecting property name: line 26 column 3 (char 792)
Found 1 bad json examples :-(
```

**Comment by zimeon** [comment]
I should perhaps highlight a couple of things:
  1. I split the option A and option B in <http://highlight-styles.iiif.io/api/presentation/2.1/#uri-representation> into separate json-doc chunks, I actually think this looks better anyway but it was needed to make each valid JSON
  2. There are few cases where we had implied continuations of lists and hashes that had a trailing comma before a comment line `\\ more stuff here`, I removed the comma in these cases so they are valid when the comment is removed

**Comment by azaroth42** [comment]
:+1: to @zimeon's commits ... Not sure if multiple author PRs fit our definition of the editorial process? If everyone contributed ... no one would be permitted to merge? :D

**Comment by jpstroop** [comment]
These feel like separate topics, and I definitely would have preferred a separate PR . That said, we're here now and none this is normative, so no harm... Unless other @IIIF/editors object, I'd say get @zimeon's tests wired up to CI and then merge.

**Comment by azaroth42** [comment]
Can someone take on the CI part? It would be good to merge sooner rather than later to avoid unnecessary merge conflicts, particularly for shuffling around the Presentation API content which will make for extensive changes that GH is likely to throw a wobbly about automerging.

**Comment by jpstroop** [comment]
Trying to figure out how it works now. If it's holding you up, go ahead and merge this and I'll make a new PR.

**Comment by zimeon** [comment]
Sorry to have made this all a bit more complicated! Thanks for getting it in the CI

**Comment by jpstroop** [comment]
:+1:

**Pull request merged**
