### PR TITLE
updated events page and added page for Toronto

### PR DESCRIPTION
**Pull request by srabun**
see: http://update_events.iiif.io/event/

and: http://update_events.iiif.io/event/2017/toronto/

### CODE REVIEW

**Comment by azaroth42** [comment]
Inner heading still says The Hague :)

**Comment by zimeon** [comment]
Do you want to push it out with "Goes here" in the TOC?

**Comment by jpstroop** [comment]
That should get replaced by a macro when the Markdown is converted, unless the Markdown is broken somewhere (on my phone, can't really see).

**Comment by srabun** [comment]
I just didn't change the first heading. It should be fixed now. I do blame jetlag in Australia.

**Comment by zimeon** [comment]
Changes look good and also include bluejeans->zoom changes, fixes #1182

**Pull request merged**
