### PR TITLE
added Harvard URL

### PR DESCRIPTION
**Pull request by rsinghal**

### CODE REVIEW

**Comment by rsinghal** [comment]
Hmm, I don't think my change caused Travis to fail?

**Comment by azaroth42** [comment]
Nope, it's our link checker failing on remote, broken sites :(

And :+1: from me. Need one for @iiif/editors to okay and merge.

**Comment by tomcrane** [comment]
:+1:

**Comment by azaroth42** [comment]
Two :+1:s = merge...

**Pull request merged**
