### PR TITLE
updated CSS and Index.html to add announcement for IIIF Consortium fo…

### PR DESCRIPTION
**Pull request by aeschylus**
…rmation.

I haven't tested this visually as I seem to be missing a configuration file that allows me to run the build process locally and serve it for inspection.

### CODE REVIEW

**Comment by aeschylus** [comment]
Running through the docs now to make sure I didn't just assume something incorrectly.

**Comment by snydman** [comment]
I asked @aeschylus  to add the news banner given the importance of the current news release.  We are unable to visually test, but if someone else @azaroth42 or @jpstroop or other can have a look to validate it would be great.  This is not urgent, but I think a useful addition give the traffic that we hope will drive to the site in the coming days.

**Comment by aeschylus** [comment]
After re-running `bundle install` I get a jekyll/mercenary error identical to this: 
https://github.com/jekyll/jekyll/issues/3084

**Comment by aeschylus** [comment]
Okay, after running `bundle exec jekyll serve`, it worked for testing. Not sure if this means I'm missing some dependencies or what, but do not merge this, it still needs tweaking.

**Comment by azaroth42** [comment]
You can always put it in a branch and look at branch.iiif.io

R

**Comment by aeschylus** [comment]
Oh, nice setup. But I just got it working.
screen shot 2015-06-18 at 11 21 32

**Comment by aeschylus** [comment]
This should be ready for someone to merge: http://quick-banner-announcement.iiif.io/

**Comment by azaroth42** [comment]
Can we make it clearer that this is breaking news? I would replace * with
the date.

**Pull request merged**
