### PR TITLE
Update Jekyll

### PR DESCRIPTION
**Pull request by jpstroop**
Replacement for #1119 ; Pins Kramdown to a version that doesn't break anchors

Could others please pull this down, install, and review?

### CODE REVIEW

**Comment by zimeon** [comment]
:+1: (or some larger number). Working fine for me, no messed up section anchors (after some bit of hell with ssl certs on rubygems...)

**Comment by jpstroop** [comment]
See https://github.com/gettalong/kramdown/issues/424#issuecomment-291959020

Just need to figure out how to pass those args to Jekyll

**Comment by zimeon** [comment]
I think the key problem is that we want GFM handling but in kramdown 13.x that implies adding section numbers to the anchors, as shown in https://github.com/gettalong/kramdown/issues/424#issuecomment-291959020, it doesn't matter about the other flags:

```
> kramdown --version
1.13.2
> echo "# 5.5 Foo Bar" | kramdown -i GFM
<h1 id="55-foo-bar">5.5 Foo Bar</h1>
> echo "# 5.5 Foo Bar" | kramdown -i GFM --auto-id-stripping
<h1 id="55-foo-bar">5.5 Foo Bar</h1>
> echo "# 5.5 Foo Bar" | kramdown -i GFM --no-auto-id-stripping
<h1 id="55-foo-bar">5.5 Foo Bar</h1>
```

**Comment by jpstroop** [comment]
@IIIF/editors + @eefahy I think this is ready.

**Comment by zimeon** [comment]
:+1:

**Comment by azaroth42** [comment]
+0 ... can't test as don't have the right ruby versions :(

**Comment by azaroth42** [comment]
:+1: from discussion.

**Comment by mikeapp** [comment]
👍

**Pull request merged**
