### PR TITLE
Auth 1.0 from 0.9.4

### LINKED ISSUE #1028: Publish auth 1.0
On today's [technical community call](https://docs.google.com/document/d/1sV5Xqq8ooFc_NO3hXbU-ZB8L2FF5FPc1reYqnpTwbeQ/edit) there was agreement to move ahead with publication of a 1.0 auth spec from [v0.9.4](http://iiif.io/api/auth/0.9/) (dated 2016-10-05) that was reviewed in [The Hague](http://iiif.io/event/2016/thehague/)

### PR DESCRIPTION
**Pull request by zimeon**
FIxes #1028. Have put Thu Jan 18 as publication date in the hope that we can get this finalized and out then. Pages to check:

  * /technical-details/ - currently have `<br/><br/>` to space buttons, should really have CSS change
  * /api/ - auth in current specs, no drafts at present
  * /api/auth/0 - now redirects to 0.9
  * /api/auth/0.9/ - added Latest Stable Version link
  * /api/auth/1 - now redirects to 1.0
  * /api/auth/1.0/ - new spec, added Latest Stable Version and Previous Version links, added to version history
  * /api/auth/1.0/implementation/ - for 1.0.0
  * /api/auth/1/login -> /api/auth/1.0/#login-interaction-pattern
  * /api/auth/1/clickthrough -> /api/auth/1.0/#clickthrough-interaction-pattern
  * /api/auth/1/kiosk -> /api/auth/1.0/#kiosk-interaction-pattern
  * /api/auth/1/external -> /api/auth/1.0/#external-interaction-pattern
  * /api/auth/1/context.json - context, namespace .../1#

and probably some things I missed...

### CODE REVIEW

**Comment by azaroth42** [comment]
:+1: from me! Hooray! :)

**Comment by mikeapp** [comment]
👍

**Comment by zimeon** [comment]
Extra paths to check:
  * /news/
  * /news/2017/01/19/auth-1-0-released/

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
Confirming 👍  after new commits.

**Comment by tomcrane** [comment]
👍

**Comment by mikeapp** [comment]
👍

**Pull request merged**
