### PR TITLE
Fix typo with physdim context/profile URIs in example Complete Response

### LINKED ISSUE #935: Image API 2.1 has wrong physdim @context URI in example
We have in http://iiif.io/api/image/2.1/#complete-response :

```
...
 "service" : [
    {
      "@context": "http://iiif.io/api/annex/service/physdim/1/context.json",
...
```

whereas in http://iiif.io/api/annex/services/#physical-dimensions it is correct as:

```
{
  "service": {
    "@context": "http://iiif.io/api/annex/services/physdim/1/context.json",
...
```

ie. must be `/services/` and not `/service/`. 

 * [x] fixed on 2.1.1 branch
 * [ ] merged to master

### PR DESCRIPTION
**Pull request by zimeon**
Fixes #935

### CODE REVIEW

**Comment by jpstroop** [comment]
:+1:

**Comment by azaroth42** [comment]
Ehhh .... shouldn't we accumulate a bunch of 2.1.1 changes together before merging to master?

**Comment by jpstroop** [comment]
I was wondering that. Probably should rename this branch to `image_211`, make that branch and merge this one into it.

**Comment by mikeapp** [comment]
👍

**Pull request merged**
